# Generated by Django 4.1.7 on 2023-03-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
