# Generated by Django 4.1.7 on 2023-03-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
